import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import { chromium } from '/Users/dkwiatkowski/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
const output=process.env.SITE_QA_OUTPUT || path.resolve(import.meta.dirname);fs.mkdirSync(output,{recursive:true});
const checks=[];const check=(name,condition)=>{assert.ok(condition,name);checks.push(name);};
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const missing=[];page.on('response',r=>{if(r.status()>=400&&r.url().startsWith('http://127.0.0.1:8790/'))missing.push({url:r.url(),status:r.status()});});
await page.goto('http://127.0.0.1:8790/presentation.html',{waitUntil:'networkidle'});
await page.waitForSelector('.session-item');
check('Six real recorded sessions are available',await page.locator('.session-item').count()===6);
check('Eight genuine demo clips are available',await page.locator('.video-choice').count()===8);
await page.screenshot({path:path.join(output,'desktop-hero.png')});
await page.locator('[data-flow="deny"]').click();
check('Denied flow clearly presents deny',await page.locator('#flow-effect').textContent()==='deny');
await page.locator('[data-flow="approval"]').click();
check('Approval flow presents exact-operation permission',await page.locator('#flow-effect').textContent()==='require_approval');
await page.waitForTimeout(1800);
await page.locator('#flow-lab').screenshot({path:path.join(output,'desktop-flow.png')});
await page.locator('[data-session="kyc-approval"]').click();
const range=page.locator('#replay-scrub');await range.focus();
await range.press('End');
check('Allowed KYC replay ends with completed executor, active session',await page.locator('#event-type').textContent()==='tool.completed'&&await page.locator('#session-state').textContent()==='active');
await range.press('Home');for(let i=0;i<3;i++)await range.press('ArrowRight');
check('KYC overwrite explicitly awaits approval',await page.locator('#event-type').textContent()==='approval.requested'&&await page.locator('#session-state').textContent()==='awaiting_approval');
await range.press('End');
await page.locator('#dashboard').screenshot({path:path.join(output,'desktop-dashboard.png')});
await page.locator('[data-session="hr-polish-violation"]').click();await range.focus();await range.press('End');
check('HR blocks model after termination',await page.locator('#event-type').textContent()==='model.denied'&&await page.locator('#session-state').textContent()==='terminated');
await page.locator('[data-session="uncertain-review-continuation"]').click();
check('Uncertain continuation begins reviewing',await page.locator('#session-state').textContent()==='reviewing');
await range.focus();await range.press('End');
check('Admin outcome is distinguished from guardian verdict',await page.locator('#event-reason').textContent()==='ADMIN_CONFIRMED_VIOLATION'&&await page.locator('#session-state').textContent()==='terminated');
await page.selectOption('#session-filter','HR');
check('Domain filter selects the correct session and limits the list',await page.locator('.session-item').count()===1&&await page.locator('#session-domain').textContent().then(t=>t.startsWith('HR')));
await page.selectOption('#session-filter','all');
await page.locator('[data-session="kyc-unseeded-embedding"]').click();await range.focus();await range.press('End');
check('Unseeded topic playback remains active and releases model answer',await page.locator('#session-state').textContent()==='active'&&await page.locator('#event-type').textContent()==='model.released');
await page.locator('#replay-reset').click();await page.selectOption('#replay-speed','750');await page.locator('#replay-play').click();await page.waitForTimeout(900);
check('Replay automatically advances through real events',!(await page.locator('#event-position').textContent()).startsWith('1/'));
await page.locator('#replay-play').click();const paused=await page.locator('#event-position').textContent();await page.waitForTimeout(850);
check('Pause stops event playback',await page.locator('#event-position').textContent()===paused);
const clips=JSON.parse(fs.readFileSync(path.resolve(process.env.SITE_QA_ROOT || path.resolve(import.meta.dirname,fs.existsSync(path.resolve(import.meta.dirname,'../source/dist'))?'../source/dist':'../published/dist'),'assets/evidence.json'))).videos;
for(const clip of clips){await page.locator(`[data-video="${clip.id}"]`).click();await page.waitForFunction(()=>{const v=document.querySelector('#demo-video');return v.readyState>=1&&Number.isFinite(v.duration);});const actual=await page.locator('#demo-video').evaluate(v=>{v.pause();return v.duration;});check(`Video metadata and playback source: ${clip.id}`,Math.abs(actual-clip.duration)<.06);}
await page.locator('#present-toggle').click();check('Presentation mode activates',await page.locator('body').evaluate(b=>b.classList.contains('presentation-mode')));
await page.waitForTimeout(1000);const startingChapter=Number((await page.locator('#slide-label').textContent()).slice(0,2));
await page.keyboard.press('ArrowRight');await page.waitForTimeout(1000);
check('Arrow key navigates to the next chapter from the current section',Number((await page.locator('#slide-label').textContent()).slice(0,2))===Math.min(9,startingChapter+1));
await page.keyboard.press('Escape');check('Escape exits presentation mode',!(await page.locator('body').evaluate(b=>b.classList.contains('presentation-mode'))));
await page.emulateMedia({reducedMotion:'reduce'});check('Reduced motion honored',await page.locator('body').evaluate(b=>b.classList.contains('reduced-motion')));
await page.setViewportSize({width:390,height:844});await page.goto('http://127.0.0.1:8790/presentation.html',{waitUntil:'networkidle'});await page.waitForSelector('.session-item');
check('Mobile has no horizontal page overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
await page.screenshot({path:path.join(output,'mobile-hero.png')});
await page.locator('#menu-toggle').click();check('Mobile navigation opens',await page.locator('#mobile-nav').isVisible());await page.locator('#mobile-nav a[href="#replay"]').click();check('Mobile navigation closes after selecting a destination',!(await page.locator('#mobile-nav').isVisible()));
await page.locator('[data-session="hr-polish-violation"]').click();await page.locator('#replay-scrub').focus();await page.locator('#replay-scrub').press('End');
await page.locator('#dashboard').screenshot({path:path.join(output,'mobile-dashboard.png')});
check('Mobile dashboard and flow have no horizontal overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
await page.locator('#kontrola').scrollIntoViewIfNeeded();await page.locator('[data-flow="approval"]').click();await page.locator('#flow-lab').screenshot({path:path.join(output,'mobile-flow.png')});
check('No missing local resources',missing.length===0);check('No uncaught browser errors',errors.length===0);
fs.writeFileSync(path.join(output,'browser-qa.json'),JSON.stringify({generated_at:new Date().toISOString(),passed:checks.length,checks,errors,missing,viewports:['1440x1000','390x844'],scope:'Local static site browser behavior and screenshot QA; no live agent backend or LLM API calls.'},null,2)+'\n');
console.log(JSON.stringify({passed:checks.length,errors,missing,screenshots:output}));
await browser.close();
